modLoader="javafml"
loaderVersion="[45,)"
license="All Rights Reserved"

[[mods]]
modId="how_to_own_a_dragon"
version="0.0.3"
displayName="How to Own a Dragon"
credits="Made with MCreator, Blockbench and a lot of people"
displayURL="https://howtoownadragon.miraheze.org/wiki/Main_Page"
logoFile="logo.png"
authors="MeAlam, Justindraak1"
description="Welcome to the Dragon world, we are trying to make this mod as canon as possible to the original HTTYD Movies and series"

[[dependencies.how_to_own_a_dragon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.how_to_own_a_dragon]]
    modId="mcreator_link"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.how_to_own_a_dragon]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

