name: Suggestion Template
description: Create a Suggestion!
title: "[Suggestion]: "
labels: ["Suggestions"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for making a Suggestion!
  - type: textarea
    id: what-should-we-add
    attributes:
      label: What do you want to have added?
      description: |
        Please tell us as detailed as possible what you want to have added to the mod!
        Feel free to also add Examples if they exist!
    validations:
      required: true
  - type: dropdown
    id: inspiration
    attributes:
      label: Inspiration
      description: Is this idea used in other Mods/Games?
      options:
        - "Yes"
        - "no"
    validations:
      required: true
  - type: input
    id: inpiration-where
    attributes:
      label: Where did you get the inspiration from?
      description: If this idea is used in a different Mod/Game, please provide a list of the Games/Mods
  - type: checkboxes
    id: related
    attributes:
      label: Type of Bug
      description: What type of bug is this?
      options:
        - label: Items/Blocks
        - label: Entity
        - label: QOL
        - label: Tools/Armor
        - label: Structure
        - label: Other
